[[redirects]]


force = true
from = "/today"
headers = {X-From = "Netlify"}
status = 302
to = "/2020-03-03"
[[redirects]]
from = "/code365startuplab"
to = "https://code-market-sell.teachable.com"


force = true
headers = {X-From = "Netlify"}
status = 302
[[redirects]]
from = "/linux"
to = "https://docs.microsoft.com/en-us/windows/wsl/install-win10"

force = true
headers = {X-From = "Netlify"}
status = 302

[[redirects]]
from = "/status"
to = "https://www.notion.so/codemarketsell/The-Making-Of-F0110W-a49983bb29e64d34a10c0ff70a65f857"

force = true
headers = {X-From = "Netlify"}
status = 302

[[redirects]]
from = "/vscode"
to = "/tools/vscode"

force = true
headers = {X-From = "Netlify"}
status = 302

[[redirects]]
from = "/tools/"
to = "https://www.notion.so/therealcasadaro/Tools-89786a2319f54faebc512290635be513"

force = true
headers = {X-From = "Netlify"}
status = 301

[[redirects]]
from = "/tools/vscode"
to = "https://code.visualstudio.com"

force = true
headers = {X-From = "Netlify"}
status = 302

[[redirects]]
from = "/tools/notion"
to = "https://www.notion.so/?r=e9e0fe2056f54e61ad80cab513d54af3"

force = true
headers = {X-From = "Netlify"}
status = 302

[[redirects]]
from = "/notion"
to = "https://www.notion.so/?r=e9e0fe2056f54e61ad80cab513d54af3"

force = true
headers = {X-From = "Netlify"}
status = 302

[[redirects]]
from = "/follow"
to = "https://www.notion.so/therealcasadaro/TRC-Net-Notes-Draft-06374f522cd94fea9087c22489f7baf8"


force = true
headers = {X-From = "Netlify"}
status = 302
[[redirects]]
from = "/project_plan"
to = "https://www.notion.so/Planning-An-App-Draft-0466b8aa6c254fd8bf1a82a3ab4c5e90"

force = true
headers = {X-From = "Netlify"}
status = 302

[[redirects]]
from = "/tools/powershell"
to = "https://docs.microsoft.com/en-us/powershell/?view=powershell-7"


force = true
headers = {X-From = "Netlify"}
status = 302
[[redirects]]
from = "/tools/grammarly"
to = "https://app.grammarly.com/"


force = true
headers = {X-From = "Netlify"}
status = 302
[[redirects]]
from = "/jamstack"
to = "https://www.notion.so/therealcasadaro/What-Is-The-JAM-Stack-c5a41c671aba43e7a60494c83b8b689e/"

force = true
headers = {X-From = "Netlify"}
status = 302

[[redirects]]
from = "/netlifydrop"
to = "https://app.netlify.com/drop"

force = true
headers = {X-From = "Netlify"}
status = 302

[[redirects]]
from = "/projects"
to = "https://www.notion.so/therealcasadaro/PROJECTS-0fccfafbf78848ddb30f75410f97bc46"


force = true
headers = {X-From = "Netlify"}
status = 302
[[redirects]]
from = "/keyboard"
to = "https://amzn.to/2RPWrxg"


force = true
headers = {X-From = "Netlify"}
status = 302
[[redirects]]
from = "/learnblender"
to = "https://www.notion.so/codemarketsell/LEARN-BLENDER-385fe281ae0643fca63d2a265ca7013c"



force = true
headers = {X-From = "Netlify"}
status = 302
[[redirects]]

from = "/TheBigIdea"
to = "https://youtu.be/Bcf9DzgN3NY"
[[redirects]]
from = "/thebigidea"
to = "/TheBigIdea"

force = true
headers = {X-From = "Netlify"}
status = 302


# BROKEN LINK

# DAILY LIVE BLOG REDIRECT

[[redirects]]
from = "/2020-01-14"
to = "https://www.notion.so/therealcasadaro/TRCNN-2020-01-14-23ca5aacc84d4f18b472c474c508f199#632cac0f72e040ee8cb5df5f6868f13b"

force = true
headers = {X-From = "Netlify"}
status = 302

[[redirects]]
from = "/2020-01-30"
to = "https://www.notion.so/2020-01-30-51c76353447c4d57ba80fd553ffdca79"

force = true
headers = {X-From = "Netlify"}
status = 302

[[redirects]]
from = "/2020-01-31"
to = "https://www.notion.so/therealcasadaro/2020-01-31-7e8bd6a8b9144a14b135ec33523ab07b"

force = true
headers = {X-From = "Netlify"}
status = 302

[[redirects]]

force = true
from = "/2020-02-01"
headers = {X-From = "Netlify"}
status = 302
to = "https://www.notion.so/therealcasadaro/2020-02-01-9af4568ca78a453792cfab50b0bfee1d"
[[redirects]]
force = true
from = "/2020-02-02"
headers = {X-From = "Netlify"}
status = 302
to = "https://www.notion.so/therealcasadaro/2020-02-02-6db808d85040467d921b060a2397c103"

[[redirects]]
force = true
from = "/2020-02-03"
headers = {X-From = "Netlify"}
status = 302
to = "https://www.notion.so/therealcasadaro/2020-02-03-f24600127bb04b89ae06cc663c264a9a"

[[redirects]]
force = true
from = "/2020-02-04"
headers = {X-From = "Netlify"}
status = 302
to = "https://www.notion.so/therealcasadaro/2020-02-04-da79f6e300914630b750c58935860a97"

[[redirects]]
force = true
from = "/2020-02-05"
headers = {X-From = "Netlify"}
status = 302
to = "https://www.notion.so/therealcasadaro/2020-02-05-2bbdea771a30469badcc4008ba1deb28"

[[redirects]]
force = true
from = "/2020-02-06"
headers = {X-From = "Netlify"}
status = 302
to = "https://www.notion.so/therealcasadaro/2020-02-07-317d5ffd2d184d8a9a2521b6977c9a61"

[[redirects]]
force = true
from = "/2020-02-07"
headers = {X-From = "Netlify"}
status = 302
to = "https://www.notion.so/therealcasadaro/2020-02-07-7351136356fe48b9855728075212c5f6"

[[redirects]]
force = true
from = "/2020-02-08"
headers = {X-From = "Netlify"}
status = 302
to = "https://www.notion.so/therealcasadaro/2020-02-08-5a3577485c8c42aa8d0d24ab02f5047d"

[[redirects]]
force = true
from = "/2020-02-09"
headers = {X-From = "Netlify"}
status = 302
to = "https://www.notion.so/therealcasadaro/2020-02-09-13e0d36a80e34e459422e9f36d95d95b"

[[redirects]]

force = true
from = "/2020-02-10"
headers = {X-From = "Netlify"}
status = 302
to = "https://www.notion.so/therealcasadaro/2020-02-10-d36b0e9746c744c1a3c72181da965c7d"
[[redirects]]
force = true
from = "/2020-02-15"
headers = {X-From = "Netlify"}
status = 302
to = "https://www.notion.so/therealcasadaro/2020-02-15-3ae60df1833d40a4ad31fe747f49539c"

[[redirects]]

force = true
from = "/2020-02-19"
headers = {X-From = "Netlify"}
status = 302
to = "https://www.notion.so/therealcasadaro/2020-02-19-d5460818c19446e38f445a075bc6c303"
[[redirects]]

force = true
from = "/2020-02-20"
headers = {X-From = "Netlify"}
status = 302
to = "https://www.notion.so/therealcasadaro/2020-02-20-9bf3b22dbc8249f38c80c27795e90ac9"
[[redirects]]

force = true
from = "/2020-02-21"
headers = {X-From = "Netlify"}
status = 302
to = "https://www.notion.so/therealcasadaro/2020-02-20-89c941c121904e7b9b73091ba17770a5"
[[redirects]]

force = true
from = "/2020-02-22"
headers = {X-From = "Netlify"}
status = 302
to = "https://www.notion.so/therealcasadaro/2020-02-21-99d5269078f044c89c7bbd0441c81ac9"
[[redirects]]

force = true
from = "/2020-02-23"
headers = {X-From = "Netlify"}
status = 302
to = "https://www.notion.so/therealcasadaro/2020-02-23-cf4d0faf4fd84b339a0aa3522cfe64b1"
[[redirects]]
force = true
from = "/2020-03-03"
headers = {X-From = "Netlify"}
status = 302
to = "https://www.notion.so/therealcasadaro/2020-03-03-a6bbe21a80994e439043ac10b1a0d647"

[[redirects]]

force = true
from = "/peaceful-warrior"
headers = {X-From = "Netlify"}
status = 302
to = "https://amzn.to/3ln6sjJ"

[[redirects]]

force = true
from = "/allstar"
headers = {X-From = "Netlify"}
status = 302
to = "https://vigilant-joliot-2f5c13.netlify.app/"

[[redirects]]

force = true
from = "/all-star"
headers = {X-From = "Netlify"}
status = 302
to = "https://vigilant-joliot-2f5c13.netlify.app/"


[[redirects]]

force = true
from = "/github"
headers = {X-From = "Netlify"}
status = 302
to = "https://github.com/therealcasadaro"

[[redirects]]
force = true
from = "streamdeck"
headers = {X-From = "Netlify"}
status = 302
to = "https://amzn.to/3vJ6Z4w"

[[redirects]]
force = true
from = "timer"
headers = {X-From = "Netlify"}
status = 302
to = "https://amzn.to/2QYHc8m"

[[redirects]]
force = true
from = "/.net"
headers = {X-From = "Netlify"}
status = 302
to = "https://amzn.to/2QYHc8m"


[[redirects]]
force = true
from = "/DotNet"
headers = {X-From = "Netlify"}
status = 302
to = "https://amzn.to/2QYHc8m"

